vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        permit:
            uri_prefix: /uploads/driverLicense
            upload_destination: '%kernel.project_dir%/public/uploads/driverLicense'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true