vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        driverLicense:
            uri_prefix: /uploads/driver_license
            upload_destination: '%kernel.project_dir%/public/uploads/driver_license'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true

        productImage:
            uri_prefix: /uploads/product_image
            upload_destination: '%kernel.project_dir%/public/uploads/product_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true

        userImage:
            uri_prefix: /uploads/user_image
            upload_destination: '%kernel.project_dir%/public/uploads/user_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true